            - name: Deploy Github Pages
  # You may pin to the exact commit or the version.
  # uses: ptienchuan/deploy-github-pages-action@abff2ab6d0300d579780d56bd3e70254c5b15403
  uses: ptienchuan/deploy-github-pages-action@1.0.0
  with:
    # [Optional] Determine the directory contains source code. Defaults to "docs"
    source-directory: # optional, default is docs
    # [Optional] Set target branch name for Github Pages. Defaults to "gh-pages"
    target-branch: # optional, default is gh-pages
    # [Optional] Set author of deploying commit. Defaults to ""
    user-name: # optional, default is github-actions[bot]
    # [Optional] Set author of deploying commit. Defaults to ""
    user-email: # optional, default is github-action[bot]@noreply.github.com
          
